/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference types="next/navigation-types/compat/navigation" />

// NOTE: This file is auto-generated by Next.js.
// It is safe to edit, but it may be overwritten.
